name: goodman_pipeline
dependencies:
  - python
  - nomkl
  - numpy
  - pandas
  - matplotlib
  - scipy
  - cython
  - pip
  - pip:
      - astropy>=5.3
      - ccdproc
      - coveralls
      - pydata-sphinx-theme
      - astroplan
      - mock
      - sphinx
      - sphinxcontrib.napoleon
